### ISSUE TITLE
Release on Stackage

### ISSUE THREAD

**Issue by prikhi** [acamino/state-codes#2]
Heya, thanks for the package. Would be great if we could install it via stack instead of having to specify it in `extra-deps`.

**Comment by acamino** [comment]
Hi, @prikhi!

Thank you for using it and sorry for the late response. This package is already on Stackage (Nightly) https://www.stackage.org/nightly-2017-09-20/package/state-codes-0.1.2. So it's just a matter of time for `state-codes` to be available on LTS.

I'll ping you as soon as the package will get released as part of LTS.

Have a great one!

**Comment by prikhi** [comment]
Wonderful, thank you :)

**Comment by acamino** [comment]
Hi @prikhi! Happy New Year! It took too long, but finally, it was released on Stackage. https://www.stackage.org/lts-10.2/package/state-codes-0.1.3.

I'm closing this issue. Thank you.
